spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080

order:
  single-pilotes-price: 1.33
  update-time-threshold-minutes: 5